### ISSUE TITLE
= convention for logging

### ISSUE THREAD

**Issue by kovacshuni** [Financial-Times/load-replicator#1]
For the possibility to search easier in splunk, from now on, whenever we log values they should be formatted like `name=value`. e.g.
`INFO - Starting load for URLs in file [%s] with rate [%d/s] until app is manually stopped.` ->
`INFO - Starting load for URLs in file=%s with rate=%d/s until app is manually stopped.`

**Comment by MihaiSorinMoisa** [comment]
Fixed in https://github.com/Financial-Times/load-replicator/commit/12fe541ce8f2f26eaac77e4814c9ec356f957fe2
